name: Releases

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build RPMs
      run: make
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*/*.rpm"
